apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    name: redis-deployment
    app: hello-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: redis-pod
      app: hello-app
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: hello-app
    spec:
      containers:
      - name: redis-container
        image: redis
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
      volumes:
      - name: cache-volume
        emptyDir: {}
