apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis-service
    app: hello-app
spec:
  type: ClusterIP
  selector:
    name: redis-pod
    app: hello-app
  ports:
    - targetPort: 6379
      port: 6379