apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    name: hello-service
    app: hello-app
spec:
  type: NodePort
  selector:
    name: hello-pod
    app: hello-app
  ports:
    - targetPort: 8000
      port: 8000
      nodePort: 30001