apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    name: hello-pod
    app: hello-app
spec:
  containers:
  - name: hello-app
    image: jrpespinas/intro-to-k8s:2
    ports:
    - containerPort: 8000