apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    name: hello-deployment
    app: hello-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: hello-pod
      app: hello-app
  template:
    metadata:
      name: hello-pod
      labels:
        name: hello-pod
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: jrpespinas/intro-to-k8s:2
