version: "3.8"
services:
  redis-service:
    image: redis
    container_name: redis-container
    ports:
      - 6379:6379
  server:
    build: .
    image: jrpespinas/intro-to-k8s:2
    container_name: server
    ports:
      - 8000:8000
    volumes:
      - .:/app

  